spring.application.name=sothat-server


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:29092}


spring.data.mongodb.uri=mongodb://root:1234@localhost:27017/sothat?authSource=admin


cors.allowed-origin=http://localhost:5173

youtube.api.key=AIzaSyAK86ZQDU3zALMrDZUoBmop3CGW9zTN1gM

logging.level.com.example.kafka_es.service=DEBUG

controller.wait-timeout-seconds=60

gpt.base-url=http://localhost:8000

gpt.path=/comments/summary/

gpt.timeout-seconds=60


