spring.application.name=sothat-server

spring.jackson.property-naming-strategy=SNAKE_CASE


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:172.31.211.130:9092}


cors.allowed-origin=http://localhost:5173

youtube.api.key=

logging.level.com.example.kafka_es.service=DEBUG

controller.wait-timeout-seconds=60

gpt.base-url=http://172.31.210.43:8000

gpt.path=/comments/summary/

gpt.timeout-seconds=60


