pipeline {
    agent any

    environment {
        IMAGE_NAME = 'boxty123/final'
        IMAGE_TAG  = 'latest'
    }

    stages {

        stage('Load Terraform Outputs') {
            steps {
                script {
                    env.ALB_DNS_NAME = sh(
                        script: "terraform output -raw alb_dns_name",
                        returnStdout: true
                    ).trim()
                }
                echo "ALB DNS: ${ALB_DNS_NAME}"
            }
        }
        stage('Docker Build and Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh '''
                    sudo docker login -u "$DOCKER_USER" --password-stdin <<< "$DOCKER_PASS"
                    sudo docker build -t boxty123/final:latest .
                    sudo docker push boxty123/final:latest
                    '''
                }
            }
        }
    }
}
