pipeline {
    agent any

    environment {
        IMAGE_NAME = 'boxty123/backend'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Git Clone') {
            steps {
                git url: 'https://github.com/So-That/sothat-server.git', branch: 'feat/visualization_api'
            }
        }
        stage('Load Terraform Outputs') {
            steps {
                script {
                    env.ALB_DNS_NAME = sh(
                        script: "terraform output -raw alb_dns_name",
                        returnStdout: true
                    ).trim()

                    env.ALB_ARN = sh(
                        script: "terraform output -raw alb_arn",
                        returnStdout: true
                    ).trim()

                    env.TARGET_GROUP_ARN = sh(
                        script: "terraform output -raw target_group_arn",
                        returnStdout: true
                    ).trim()
                }

                echo "ALB DNS NAME = ${env.ALB_DNS_NAME}"
            }
        }
        stage('Docker Build and Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker build -t $IMAGE_NAME:$IMAGE_TAG .
                    docker push $IMAGE_NAME:$IMAGE_TAG
                    docker logout
                    '''
                }
            }
        }
    }
 }
